### ISSUE TITLE
Disconnecting if connection is idle

### ISSUE THREAD

**Issue by alexeykuzub** [ostcar/goasgiserver#8]
Hello! I am using Geiss instead of Daphne. When I connect to the server and some time (about 60 sec.) don't send some message to this socket, the connection is closing. Is there some way to increase the time to disconnect?

**Comment by matthiask** [comment]
Are you using Geiss behind nginx by chance? It might be nginx (or some other proxying software) terminating your connections.

Maybe you should take a look at `proxy_read_timeout` then, or maybe send periodic keepalive packets (which might be a good idea anyway, because then the websocket client might detect its own disconnection earlier and reconnect if you're using `ReconnectingWebsocket` or something similar)

**Comment by alexeykuzub** [comment]
Oh, yeah! Sorry, I'm using Geiss behind nginx. Thank you. But when I used Daphne this problem didn't exist.

**Comment by alexeykuzub** [comment]
But `proxy_read_timeout` solved my problem! Thank you!
